apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: btrfs-fast
provisioner: subvol.io/provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
parameters:
  driver: btrfs
  mountPrefix: /mnt/btrfs-pool/k8s
  pathTemplate: "{{ .Namespace }}/{{ .PVC }}"
  defaultOwner: "1000:1000"
  defaultMode: "0750"
