package controller

import (
	"bytes"
	"fmt"
	"path"
	"strconv"
	"strings"
	"text/template"

	"github.com/blesswinsamuel/k8s-subvol-provisioner/pkg/apis/config"
	corev1 "k8s.io/api/core/v1"
)

// ExtractTemplateContext builds a TemplateContext from a PVC and StorageClass name.
func ExtractTemplateContext(pvc *corev1.PersistentVolumeClaim, scName string) config.TemplateContext {
	ctx := config.TemplateContext{
		Namespace:    pvc.Namespace,
		PVC:          pvc.Name,
		StorageClass: scName,
		Labels:       pvc.Labels,
		Annotations:  pvc.Annotations,
	}

	claimName, owner, index, ok := ParseStatefulSetPVC(pvc.Name)
	if ok {
		ctx.ClaimName = claimName
		ctx.Owner = owner
		ctx.Index = index
	} else {
		ctx.ClaimName = pvc.Name
		ctx.Owner = pvc.Name
	}

	return ctx
}

// ParseStatefulSetPVC parses a PVC name generated by a StatefulSet: "<claimTemplate>-<statefulset>-<index>"
func ParseStatefulSetPVC(pvcName string) (claimName, owner, index string, ok bool) {
	lastHyphen := strings.LastIndex(pvcName, "-")
	if lastHyphen <= 0 || lastHyphen == len(pvcName)-1 {
		return "", "", "", false
	}

	idxStr := pvcName[lastHyphen+1:]
	if _, err := strconv.Atoi(idxStr); err != nil {
		return "", "", "", false
	}

	prefix := pvcName[:lastHyphen]
	firstHyphen := strings.Index(prefix, "-")
	if firstHyphen <= 0 {
		return prefix, prefix, idxStr, true
	}

	return prefix[:firstHyphen], prefix[firstHyphen+1:], idxStr, true
}

// EvaluatePathTemplate evaluates a Go template string against the template context.
func EvaluatePathTemplate(tmplStr string, ctx config.TemplateContext) (string, error) {
	if strings.TrimSpace(tmplStr) == "" {
		tmplStr = "{{ .Namespace }}/{{ .PVC }}"
	}

	tmpl, err := template.New("path").Parse(tmplStr)
	if err != nil {
		return "", fmt.Errorf("invalid path template %q: %w", tmplStr, err)
	}

	buf := bytes.NewBuffer(nil)
	if err := tmpl.Execute(buf, ctx); err != nil {
		return "", fmt.Errorf("failed to evaluate path template %q: %w", tmplStr, err)
	}

	cleaned := path.Clean(strings.Trim(buf.String(), "/ "))
	if strings.HasPrefix(cleaned, "..") || strings.Contains(cleaned, "/../") {
		return "", fmt.Errorf("unsafe path evaluated from template: %q", cleaned)
	}

	return cleaned, nil
}
